### ISSUE TITLE
Display Lettered Partitions and Other Internal Drives in Sidebar

### ISSUE THREAD

**Issue by z0oinks** [duke7553/files-uwp#1]
My D: drive, as well as any other drives I plug into the computer, do not show in the sidebar.

Due to this, there is no way to access them

**Comment by duke7553** [comment]
Mostly fixed as of latest release. Give it a try ;)

**Comment by Yash-Kaveeshwar** [comment]
It is still not working
![2019-02-13](https://user-images.githubusercontent.com/26587446/52680846-ff1d0000-2f5f-11e9-9b91-9dae2090e862.png)
![2019-02-13 1](https://user-images.githubusercontent.com/26587446/52680856-06440e00-2f60-11e9-96df-df8b47a82c80.png)

**Comment by duke7553** [comment]
It should work with USB Drives... is that an actual separate drive, or a partition of your existing drive with a letter assigned? Reopening this issue.

**Comment by Yash-Kaveeshwar** [comment]
my drive partation E is not showing up and cd drive F is showing as removable drive

**Comment by LER0ever** [comment]
Same here.
I have C: and D: on the internal SSD drive, and E: F: on the internal HDD. But none of the drives other than C is shown in the Files. 

- Windows 10 1809 17763.282 x64
- Files version 0.4.6
- Gave the file access permission for the app
- Dev mode enabled

![image](https://user-images.githubusercontent.com/10568668/52682853-876eb700-2f06-11e9-826c-9d9f2b5c734b.png)

**Comment by duke7553** [comment]
Ok. That makes sense. When I implemented the feature, it was intended to only display "Removable Drives" like individual USBs or DVDs. I'll try to rework the feature soon to scan and display all drive letters, rather than the subset that are removable. Thanks for reporting this.

**Comment by duke7553** [comment]
![snipofdrives](https://user-images.githubusercontent.com/20365014/52749866-7bdbc880-2fb8-11e9-8dd2-ab3cf9a17a16.jpg)
This will be fixed very soon.

**Comment by duke7553** [comment]
Fixed in v0.4.7
