### ISSUE TITLE
v0.8.1 Crashes when launching

### ISSUE THREAD

**Issue by yaichenbaum** [duke7553/files-uwp#803]
I just updated to v0.8.1 and it crashes when launching the application.

**Comment by fabioromeo** [comment]
Same issue here, app crashes even after reinstalling and clearing data.

**Comment by tsvietOK** [comment]
@yair100 v0.8.1 working fine for me. 20/20 successful starts.

**Comment by fabioromeo** [comment]
> 
> 
> Same issue here, app crashes even after reinstalling and clearing data.

Weirdly enough, after rebooting the machine I could open the app.

**Comment by SOI7** [comment]
It's kinda random, I'm able to use the app after several boots

**Comment by yaichenbaum** [comment]
This issue has been fixed with the v0.8.2 release.

**Comment by GittyMac** [comment]
0.8.2 still crashes for me with a Windows.UI.XAML.dll crash.
